### ISSUE TITLE
Need re-dump autoload after an installation

### ISSUE THREAD

**Issue by hidenorigoto** [koriym/PHP.Skeleton#13]
Autoload files are invalid after an installation.

For instance, I run the `phpunit` command right after installation but it fails
```
Fatal error: Class 'Example\Hello\Hello' not found in
/xxxxx/Example.Hello/tests/Example/Hello/HelloTest.php on line 14
```

After running `composer dump-autoload`, phpunit runs successfully.

So, installer should re-dump autoload files after generating a composer.json.

**Comment by kumamidori** [comment]
@koriym レスが遅くなりすみませんでした。

いったん名前空間を全部破棄しないと、そうする前にダンプをかけても効かないことが分かりました。
タイムラグをつけて別プロセスを立ち上げてダンプイベントをかける、とかすれば、やりたいことはできるのかもしれませんが、それはあまりうまくないやり方のように思います。
実装方法が不明ということで、クローズ頂いてかまいません。

ユーザ向けに、dump-autoload を自分で一度やってくださいね、という独自メッセージを出す方が、ユーザビリティは上がるかなと思ったのですが、どうでしょうかね。

**Comment by kenjis** [comment]
これでどうでしょう？

#18

それから、上記に含めてますが、現在の develop では composer.json の名前空間の置換が漏れています。

**Comment by koriym** [comment]
@kumamidori @kenjis 解決ですね！

**Comment by kenjis** [comment]
あ、フォルダ名のバリデーションにバグが残ってました。別途 PR します。

**Comment by kumamidori** [comment]
ありがとうございました>< :+1:
