### ISSUE TITLE
Giving credit to this package

### ISSUE THREAD

**Issue by jrumbut** [koriym/PHP.Skeleton#30]
I'm currently developing an MIT licensed package using this skeleton. I'd like to recognize the author(s) of this code and point future developers to this resource.

Do you have a snippet to be added to the license file (and perhaps the README) for this? Could it become a part of the skeleton itself?

Thank you for your work!

**Comment by koriym** [comment]
Hello jrumbut

Thank you for using my package and feedback !
"Akihito Koriyama (akihito.koriyama@gmail.com)"( or anything similar like this) is fine for the credit.

**Comment by koriym** [comment]
@jrumbut 

Let me know when you release your project. I'm curious to see it !

**Comment by jrumbut** [comment]
Hey! Finally added the line you suggested here: https://github.com/jrumbut/eloquent-memoize

**Comment by koriym** [comment]
Wow ! @jrumbut thank you !
