### ISSUE TITLE
package name question in create-project does not work(v1.1.6)

### ISSUE THREAD

**Issue by 77web** [koriym/PHP.Skeleton#56]
my php versions are 7.3.11, 7.4.7. both effected.

```
> Koriym\PhpSkeleton\Installer::preInstall

What is the vendor name?
(MyVendor): Quartetcom

What is the package name?
(MyPackage): Quartetcom

MyPackage
```

I typed "Quartetcom" at vendor name, then package name was also set to "Quartetcom" automatically. (strange)
I tried to type some new package name there, not accepted.

**Comment by koriym** [comment]
I can't reproduce the issue...

I type "Quartetcom" at the vendor name, then it works as expected.

![image](https://user-images.githubusercontent.com/529021/98522707-5debe680-22b8-11eb-89b1-2b4b130da34e.png)

**Comment by koriym** [comment]
Please review.
https://github.com/koriym/Koriym.PhpSkeleton/blob/1.x/src/Installer.php#L70-L72

**Comment by 77web** [comment]
@koriym 
Thanks!
By the way, my composer is 1.x (not 2.x). Is it related?

**Comment by 77web** [comment]
hmm, I cannot reproduce it at my laptop. 
```
hiromi@Hiromi-no-MacBook-Air qc_projects % composer --version
Composer version 1.10.1 2020-03-13 20:34:27
hiromi@Hiromi-no-MacBook-Air qc_projects % php -v
PHP 7.3.11 (cli) (built: Jun  5 2020 23:50:40) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
```

I'll try again at my desktop :thinking:

**Comment by 77web** [comment]
same again in my desktop...

```
***@quartet92 projects % composer --version
Composer version 1.10.13 2020-09-09 11:46:34
***@quartet92 projects % php -v            
PHP 7.4.7 (cli) (built: Jun 22 2020 13:24:49) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.7, Copyright (c), by Zend Technologies
    with Xdebug v2.9.6, Copyright (c) 2002-2020, by Derick Rethans
```

**Comment by 77web** [comment]
desktop:

```
> pre-update-cmd: Koriym\PhpSkeleton\Installer::preInstall

What is the vendor name?
(MyVendor): Quartetcom

What is the package name?
(MyPackage): Quartetcom
Quartetcom
Quartetcom
```

This time I typed "Quartetcom" at dialogue and it was accepted.
But the question shows MyVendor answer from the first view, so strange and confusing. 
```
What is the package name?
(MyPackage): Quartetcom
```

MyPackageの質問が表示された瞬間からすでにMyVendorの答えが答えのように表示されています。
その状態でenterすると "MyPackage" が入力された扱いとなります。

**Comment by 77web** [comment]
I updated composer in both env, but my desktop is still in the same state with composer v1.10.17 on php 7.3 & 7.4.
my laptop is ok.

**Comment by koriym** [comment]
```
composer self-update --1
Upgrading to version 1.10.17 (1.x channel).
```

```
What is the vendor name?
(MyVendor): Quartetcom
Quartetcom

What is the package name?
(MyPackage): Quartetcom
Quartetcom
```

All same with composer 1.x also. Umm..

**Comment by koriym** [comment]
問題は入力ではなく表示だけですか？
Windows?

**Comment by 77web** [comment]
@koriym はい、結果的に表示だけでした。macです。

**Comment by 77web** [comment]
I confirmed that it does not happen with php-skeleton v1.1.5.

**Comment by kenjis** [comment]
I can't reproduce it either.

- Mac
- koriym/php-skeleton (1.1.6)
- PHP 7.3.20 (cli) (built: Jul  9 2020 23:55:30) ( NTS )
- Composer version 1.10.8 2020-06-24 21:23:30

<img width="391" alt="スクリーンショット 2020-11-10 9 38 23" src="https://user-images.githubusercontent.com/87955/98612904-85829380-2338-11eb-9d0f-9e29ef3c3272.png">

**Comment by koriym** [comment]
@77web Still wondering why only @77web has a issue. @kenjis Any ideas?

**Comment by koriym** [comment]
Confirmed with new M1 mac with arm PHP8.

**Comment by 77web** [comment]
@koriym It might be related with my shell environment 🤔 
I first set up the desktop with this issue several years ago, and actually I was not familiar with shell setting at that time. I googled and applied some tips from some of blog articles then. So my shell might be broken...

**Comment by koriym** [comment]
@77web Try again with a new (temporary created) user?

**Comment by kenjis** [comment]
I don't understand the situation of @77web clearly.

> I typed "Quartetcom" at vendor name, then package name was also set to "Quartetcom" automatically. (strange)
> I tried to type some new package name there, not accepted.

Do you mean when you type new package name, there is no change at all in the terminal output?
Do you have to type return key to go next?
Even if you type something new name, the package name is always `Quartetcom`?

> MyPackageの質問が表示された瞬間からすでにMyVendorの答えが答えのように表示されています。
その状態でenterすると "MyPackage" が入力された扱いとなります。

Does this behave differently from the first issue?

Anyway it seems the issue is on the @77web environment, but I have no idea what makes it.
Something is taking away the standard input?

**Comment by koriym** [comment]
Unless we find another case, maybe it's better to revert?
@77web How was the new user test? or any thoughts?

**Comment by 77web** [comment]
@koriym 

The issue was not reproduced with guest users.
So it's may be related to my shell environment.

**Comment by koriym** [comment]
@77web Thanks for the confirmation.
Would you mind give me a revert PR, please?

**Comment by koriym** [comment]
Thanks.
